import numpy as np
print("Addition of array is...")
array1=np.array([1,2,3])
array2=np.array([4,5,6])
array3=np.add(array1,array2)
print(array1)
print(array2)
print("addition is:",array3)
print("Multiplication of array...")
array4=np.multiply(array1,array2)
print("multiplication is",array4)
